version: '2'
services:
  saga-db:
    image: mongo:latest
    container_name: "saga.softwaredulce.me"
    environment:
    - MONGODB_USER=admin
    - MONGODB_PASS=password
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    - MONGODB_DATABASE=saga
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
